name: Your New Jekyll Site
highlighter: pygments

url: "https://www.noname-ev.de"
baseurl: ""

treff_lat: 49.417433
treff_lon: 8.675255

map_js: |
  L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
    attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors',
  maxZoom: 18,
  detectRetina: true
  }).addTo(map);
